### ISSUE TITLE
Unescape strings in confirmation page and confirmation email

### ISSUE THREAD

**Issue by shankie-codes** [joshcanhelp/proper-contact-form#1]
Hi chaps,

Great plugin. We at Proper Design (a weird coincidence naming-wise!) love it!

One slight issue I've noticed – the confirmation page and confirmation email don't unescape strings, so we end up with backslashes and the like if we put single or double quotes in the messages.

I could do a PR on this, but am a bit busy at the moment and will probably take you seconds to sort out.

Let me know if you get a chance, otherwise I'll do a PR.

Cheers

**Comment by joshcanhelp** [comment]
Hey there, 

Thank you for the heads up. I have another minor issue that needs correcting soon so I'll add this to the list. 

Proper Power!

**Comment by shankie-codes** [comment]
Proper^2!

Cheers Josh, looking forward to it. In the mean time, I've written confirmation text without special characters :)
